mutation addAccountAddressBookEntryMutation($input: AddAccountAddressBookEntryInput!) {
  addAccountAddressBookEntry(input: $input) {
    address {
      _id
      description
      address
      reference
      geolocation{
        latitude
        longitude
      }
    }
  }
}

mutation updateAccountAddressBookEntryMutation($input: UpdateAccountAddressBookEntryInput!) {
  updateAccountAddressBookEntry(input: $input) {
    address {
      _id
      description
      address
      reference
      geolocation{
        latitude
        longitude
      }
    }
  }
}

mutation removeAccountAddressBookEntryMutation($input: RemoveAccountAddressBookEntryInput!) {
  removeAccountAddressBookEntry(input: $input) {
    address {
      _id
      description
      address
      reference
      geolocation{
        latitude
        longitude
      }
    }
  }
}
