query viewer {
  viewer {
    _id
    addressBook {
      edges{
        node {
          _id
          description
          address
          reference
          geolocation {
            latitude
            longitude
          }
        }
      }
      
    }
    emailRecords {
      address
    }
    name
    primaryEmailAddress
  }
}